/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kerjaproject;

import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.util.JRLoader;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Kevin
 */
public class home extends javax.swing.JFrame {
  Connection con;
    Statement st;
    ResultSet rs;
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        //        Mmbuat ID Penumpang Otomatis
        autoid();
//        Memanggil Nama Kereta Api
//        kereta();
//        Mengambil Tanggal Sekarang
        Date date = new Date();
        tglpembelian.setDate(date);
//        Memanggil Data Kelas
       // kelas();
      // harga1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bandara_tujuan = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        maskapai = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sdewasa = new javax.swing.JSpinner();
        fbayar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ckelas = new javax.swing.JComboBox<String>();
        ltotal = new javax.swing.JLabel();
        lkembali = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        falamat = new javax.swing.JTextField();
        hdewasa = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        bandara_awal = new javax.swing.JTextField();
        berangkat = new javax.swing.JLabel();
        tiba = new javax.swing.JLabel();
        btnsimpan2 = new javax.swing.JButton();
        bayangan4 = new javax.swing.JSpinner();
        bayangan5 = new javax.swing.JTextField();
        bayangan1 = new javax.swing.JTextField();
        bayangan2 = new javax.swing.JTextField();
        bayangan3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bayangan6 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        tglpembelian = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel2PropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Nama Penumpang :");

        fnama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Bandara awal       : ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Tujuan                :");

        bandara_tujuan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bandara_tujuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Bandara Internasional Sultan Aji Muhammad Sulaiman Sepinggan, Balikpapan (BPN)", "Bandara Internasional Syamsudin Noor, Banjarmasin (BDJ)", "Bandara Internasional Hang Nadim, Batam (BTH)", "Bandara Internasional I Gusti Ngurah Rai, Denpasar (DPS)", "Bandara Internasional Kualanamu, Medan (KNO)", "Bandara Internasional Sultan Mahmud Badaruddin II, Palembang (PLM)" }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("ID Penumpang      :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Rp.");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Total         :");

        fid.setEditable(false);
        fid.setBackground(new java.awt.Color(204, 204, 255));
        fid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Maskapai            :");

        maskapai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maskapai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Lion Air", "Batik Air", "Indonesia AirAsia", "Super Air Jet", "Citilink" }));
        maskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maskapaiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Bayar        :");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Kembali     :");

        sdewasa.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        sdewasa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdewasadewasa(evt);
            }
        });

        fbayar.setBackground(new java.awt.Color(204, 204, 255));
        fbayar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fbayarbayar(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Kelas                  :");

        ckelas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ckelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Eksekutif", "Ekonomi ", " " }));
        ckelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckelaskelas(evt);
            }
        });

        ltotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ltotal.setText("Rp. 0");

        lkembali.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lkembali.setText("Rp. 0");
        lkembali.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lkembaliInputMethodTextChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Alamat                 :");

        falamat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        hdewasa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hdewasa.setText("0");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("/ Org");

        bandara_awal.setEditable(false);
        bandara_awal.setBackground(new java.awt.Color(204, 204, 255));
        bandara_awal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bandara_awal.setText("Bandara Halim PerdanaKusuma");

        berangkat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        berangkat.setText("00.00 WIB");

        tiba.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tiba.setText("00.00 WIB");

        btnsimpan2.setBackground(new java.awt.Color(255, 255, 255));
        btnsimpan2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnsimpan2.setText("Simpan");
        btnsimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan2ActionPerformed(evt);
            }
        });

        bayangan4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        bayangan4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bayangan4dewasa(evt);
            }
        });

        bayangan5.setEditable(false);

        bayangan1.setEditable(false);
        bayangan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayangan1ActionPerformed(evt);
            }
        });

        bayangan2.setEditable(false);

        bayangan3.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Berangkat :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Harga        :");

        bayangan6.setEditable(false);
        bayangan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayangan6ActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jToggleButton1.setText("Kembali");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        tglpembelian.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Tgl Pembelian  :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(falamat, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(sdewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel9)
                                                .addGap(8, 8, 8)
                                                .addComponent(hdewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel25))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(berangkat)
                                .addGap(89, 89, 89)
                                .addComponent(tiba)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnsimpan2)
                                .addGap(85, 85, 85)
                                .addComponent(jToggleButton1)
                                .addGap(36, 36, 36)
                                .addComponent(bayangan6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bandara_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bandara_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckelas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(108, 108, 108)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bayangan5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bayangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bayangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bayangan3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bayangan4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel14))
                                                .addGap(16, 16, 16))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(tglpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(berangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(falamat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(bandara_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bandara_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ckelas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(sdewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hdewasa)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel11)))
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(tglpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bayangan5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bayangan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bayangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bayangan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bayangan4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bayangan6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan2)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Admin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Keluar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Penumpang");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2laporan(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void autoid(){
       try{
            con = Koneksi.getKoneksi();
            String sql = "SELECT COUNT(id) as kode FROM penumpang";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                String kode = rs.getString("kode");
                int a = Integer.parseInt(kode);
                int b = a+1;
                fid.setText("IR. "+b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Admin().setVisible(true);
        dispose();
 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2laporan(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2laporan
        new Penumpang().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2laporan

    private void maskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maskapaiActionPerformed

        if(maskapai.getSelectedItem().equals("Lion Air")){
            bayangan4.setValue(1);
            maskapai.setSelectedIndex(1);
        }else if(maskapai.getSelectedItem().equals("Batik Air")){
            bayangan4.setValue(2);
            maskapai.setSelectedIndex(2);
        }
        else if(maskapai.getSelectedItem().equals("Indonesia AirAsia")){
            bayangan4.setValue(3);
            maskapai.setSelectedIndex(3);
        }
         else if(maskapai.getSelectedItem().equals("Super Air Jet")){
            bayangan4.setValue(4);
            maskapai.setSelectedIndex(4);
        }
        else if(maskapai.getSelectedItem().equals("Citilink")){
            bayangan4.setValue(5);
            maskapai.setSelectedIndex(5);
        }

        if(maskapai.getSelectedItem().equals("Lion Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Aji Muhammad Sulaiman Sepinggan, Balikpapan (BPN)")){
            berangkat.setText("08.30 WIB");
            tiba.setText("13:25 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Lion Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Syamsudin Noor, Banjarmasin (BDJ)")){
            berangkat.setText("06.30 WIB");
            tiba.setText("14:30 WITA");
             
        }else if(maskapai.getSelectedItem().equals("Lion Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Hang Nadim, Batam (BTH)")){
            berangkat.setText("07:20 WIB");
            tiba.setText("15:45 WIB");
          
        }else if(maskapai.getSelectedItem().equals("Lion Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional I Gusti Ngurah Rai, Denpasar (DPS))")){
            berangkat.setText("06:15 WIB");
            tiba.setText("13:45 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Lion Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Kualanamu, Medan (KNO)")){
            berangkat.setText("09:10 WIB");
            tiba.setText("12:30 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Lion Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Mahmud Badaruddin II, Palembang (PLM)")){
            berangkat.setText("09.10 WIB");
            tiba.setText("14:03 WIB");
           
        }
        
        //Batik Air
        else if (maskapai.getSelectedItem().equals("Batik Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Aji Muhammad Sulaiman Sepinggan, Balikpapan (BPN)")){
            berangkat.setText("09.30 WIB");
            tiba.setText("13:45 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Batik Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Syamsudin Noor, Banjarmasin (BDJ)")){
            berangkat.setText("07:30 WIB");
            tiba.setText("15:20 WITA");
             
        }else if(maskapai.getSelectedItem().equals("Batik Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Hang Nadim, Batam (BTH)")){
            berangkat.setText("08:00 WIB");
            tiba.setText("13:00 WIB");
          
        }else if(maskapai.getSelectedItem().equals("Batik Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional I Gusti Ngurah Rai, Denpasar (DPS))")){
            berangkat.setText("06:30 WIB");
            tiba.setText("13:00 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Batik Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Kualanamu, Medan (KNO)")){
            berangkat.setText("09:25 WIB");
            tiba.setText("12:45 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Batik Air") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Mahmud Badaruddin II, Palembang (PLM)")){
            berangkat.setText("09.40 WIB");
            tiba.setText("14:30 WIB");
           
        

            //Indonesia AirAsia
        }else if(maskapai.getSelectedItem().equals("Indonesia AirAsia") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Aji Muhammad Sulaiman Sepinggan, Balikpapan (BPN)")){
            berangkat.setText("10.30 WIB");
            tiba.setText("13:30 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Indonesia AirAsia") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Syamsudin Noor, Banjarmasin (BDJ)")){
            berangkat.setText("08.30 WIB");
            tiba.setText("15:30 WITA");
             
        }else if(maskapai.getSelectedItem().equals("Indonesia AirAsia") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Hang Nadim, Batam (BTH)")){
            berangkat.setText("07:40 WIB");
            tiba.setText("15:30 WIB");
          
        }else if(maskapai.getSelectedItem().equals("Indonesia AirAsia") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional I Gusti Ngurah Rai, Denpasar (DPS))")){
            berangkat.setText("07:30 WIB");
            tiba.setText("13:45 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Indonesia AirAsia") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Kualanamu, Medan (KNO)")){
            berangkat.setText("10:30 WIB");
            tiba.setText("12:19 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Indonesia AirAsia") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Mahmud Badaruddin II, Palembang (PLM)")){
            berangkat.setText("09.20 WIB");
            tiba.setText("15:30 WIB");
           
        }
        
        //Super Air jet
        else if(maskapai.getSelectedItem().equals("Super Air jet") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Aji Muhammad Sulaiman Sepinggan, Balikpapan (BPN)")){
            berangkat.setText("09.30 WIB");
            tiba.setText("14:25 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Super Air jet") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Syamsudin Noor, Banjarmasin (BDJ)")){
            berangkat.setText("05.30 WIB");
            tiba.setText("13:25 WITA");
             
        }else if(maskapai.getSelectedItem().equals("Super Air jet") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Hang Nadim, Batam (BTH)")){
            berangkat.setText("06:20 WIB");
            tiba.setText("15:20 WIB");
          
        }else if(maskapai.getSelectedItem().equals("Super Air jet") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional I Gusti Ngurah Rai, Denpasar (DPS))")){
            berangkat.setText("07:15 WIB");
            tiba.setText("12:45 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Super Air jet") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Kualanamu, Medan (KNO)")){
            berangkat.setText("07:10 WIB");
            tiba.setText("14:30 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Super Air jet") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Mahmud Badaruddin II, Palembang (PLM)")){
            berangkat.setText("09.15 WIB");
            tiba.setText("14:05 WIB");
           
        }
             //Citilink
        else if(maskapai.getSelectedItem().equals("Citilink") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Aji Muhammad Sulaiman Sepinggan, Balikpapan (BPN)")){
            berangkat.setText("07:15 WIB");
            tiba.setText("12:40 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Citilink") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Syamsudin Noor, Banjarmasin (BDJ)")){
            berangkat.setText("05.30 WIB");
            tiba.setText("13:15 WITA");
             
        }else if(maskapai.getSelectedItem().equals("Citilink") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Hang Nadim, Batam (BTH)")){
            berangkat.setText("08:20 WIB");
            tiba.setText("15:00 WIB");
          
        }else if(maskapai.getSelectedItem().equals("Citilink") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional I Gusti Ngurah Rai, Denpasar (DPS))")){
            berangkat.setText("07:15 WIB");
            tiba.setText("12:45 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Citilink") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Kualanamu, Medan (KNO)")){
            berangkat.setText("10:10 WIB");
            tiba.setText("12:40 WITA");
            
        }else if(maskapai.getSelectedItem().equals("Citilink") && bandara_tujuan.getSelectedItem().equals("Bandara Internasional Sultan Mahmud Badaruddin II, Palembang (PLM)")){
            berangkat.setText("08.10 WIB");
            tiba.setText("12:10 WIB");
           
        }
    }//GEN-LAST:event_maskapaiActionPerformed

    private void sdewasadewasa(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdewasadewasa
        int a = (int) sdewasa.getValue();
        int b = Integer.parseInt(hdewasa.getText());
        int c = a*b;
        ltotal.setText("Rp. "+c);
        bayangan1.setText(""+c);

    }//GEN-LAST:event_sdewasadewasa

    private void fbayarbayar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fbayarbayar

    }//GEN-LAST:event_fbayarbayar

    private void ckelaskelas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckelaskelas

        if(ckelas.getSelectedItem().equals("Bisnis")){
            bayangan5.setText("bisnis");
        }else if(ckelas.getSelectedItem().equals("Ekonomi Premium")){
            bayangan5.setText("ekonomipremium");
        }else if(ckelas.getSelectedItem().equals("Ekonomi")){
            bayangan5.setText("ekonomi");
        }else if(ckelas.getSelectedItem().equals("Kelas Satu")){
            bayangan5.setText("kelassatu");
        }

        con = Koneksi.getKoneksi();

        if((ckelas.getSelectedItem().equals("bisnis"))){
            try{
                st = con.createStatement();
                String sql1 = "SELECT * FROM harga WHERE id='3'";
                rs = st.executeQuery(sql1);
                while(rs.next()){
                    hdewasa.setText(rs.getString("harga"));
                }
               
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }else if((ckelas.getSelectedItem().equals("Ekonomi Premium "))){
            try{
                st = con.createStatement();
                String sql1 = "SELECT * FROM harga WHERE id='2'";
                rs = st.executeQuery(sql1);
                while(rs.next()){
                    hdewasa.setText(rs.getString("harga"));
                }
              
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
        else if((ckelas.getSelectedItem().equals("Ekonomi "))){
            try{
                st = con.createStatement();
                String sql1 = "SELECT * FROM harga WHERE id='5'";
                rs = st.executeQuery(sql1);
                while(rs.next()){
                    hdewasa.setText(rs.getString("harga"));
                }
              
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
         else if((ckelas.getSelectedItem().equals("Eksekutif"))){
            try{
                st = con.createStatement();
                String sql1 = "SELECT * FROM harga WHERE id='4'";
                rs = st.executeQuery(sql1);
                while(rs.next()){
                    hdewasa.setText(rs.getString("harga"));
                }
              
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
    }//GEN-LAST:event_ckelaskelas

    private void btnsimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan2ActionPerformed
       String jrxmlFile = "E:\\KerjaProject\\src\\report\\Tiket.jrxml";
       String jasperFile = "E:\\KerjaProject\\src\\report\\Tiket.jasper";
        try{ 
        con = Koneksi.getKoneksi();
            String sql = "INSERT INTO penumpang VALUES('"+fid.getText()+"','"+fnama.getText()+"','"+falamat.getText()+"','"+bandara_awal.getText()+"','"+bandara_tujuan.getSelectedItem()+"','"+berangkat.getText()+"','"+tiba.getText()+"','"+tanggal.getDate()+"','"+maskapai.getSelectedItem()+"','"+ckelas.getSelectedItem()+"','"+sdewasa.getValue()+"','"+ltotal.getText()+"','"+tglpembelian.getDate()+"','"+fbayar.getText()+"','"+lkembali.getText()+"')";
            st = con.createStatement();
            st.execute(sql);
            this.dispose();
            index.oke();
           JasperCompileManager.compileReportToFile(jrxmlFile, jasperFile);
            HashMap parameter = new HashMap();
            parameter.put("per_id",this.fid.getText());
             JasperPrint jPrint = JasperFillManager.fillReport(jasperFile, parameter, Koneksi.getKoneksi());
            JasperViewer.viewReport(jPrint, false);
            
        }  catch (Exception e) {
    e.printStackTrace();}     // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpan2ActionPerformed

    private void bayangan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayangan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayangan1ActionPerformed

    private void jPanel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel2PropertyChange
        bayangan1.setVisible(false);
        bayangan2.setVisible(false);
        bayangan3.setVisible(false);
        bayangan4.setVisible(false);
        bayangan5.setVisible(false); 
        bayangan6.setVisible(false); 
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel2PropertyChange

    private void lkembaliInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lkembaliInputMethodTextChanged
           // TODO add your handling code here:
    }//GEN-LAST:event_lkembaliInputMethodTextChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    try {
    String hargaText = fbayar.getText();
    String totalText = ltotal.getText();
    String numericString = totalText.replaceAll("[^\\d,]", "");
    numericString = numericString.replace(",", "");
    int harga = Integer.parseInt(hargaText);
    int total = Integer.parseInt(numericString);

    // Check if ltotal is less than fbayar
    if (harga < total) {
        lkembali.setText("Rp. 0");
        bayangan6.setText("0");
    } else {
        int kembalian = harga - total;
        lkembali.setText("Rp. " + kembalian);
        bayangan6.setText("" + kembalian);
    }
} catch (NumberFormatException e) {
    System.err.println("Error: " + e.getMessage());
}
 // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidActionPerformed

    private void bayangan4dewasa(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bayangan4dewasa

    }//GEN-LAST:event_bayangan4dewasa

    private void bayangan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayangan6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayangan6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bandara_awal;
    private javax.swing.JComboBox<String> bandara_tujuan;
    private javax.swing.JTextField bayangan1;
    private javax.swing.JTextField bayangan2;
    private javax.swing.JTextField bayangan3;
    private javax.swing.JSpinner bayangan4;
    private javax.swing.JTextField bayangan5;
    private javax.swing.JTextField bayangan6;
    private javax.swing.JLabel berangkat;
    private javax.swing.JButton btnsimpan2;
    private javax.swing.JComboBox<String> ckelas;
    private javax.swing.JTextField falamat;
    private javax.swing.JTextField fbayar;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fnama;
    private javax.swing.JLabel hdewasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lkembali;
    private javax.swing.JLabel ltotal;
    private javax.swing.JComboBox<String> maskapai;
    private javax.swing.JSpinner sdewasa;
    private com.toedter.calendar.JDateChooser tanggal;
    private com.toedter.calendar.JDateChooser tglpembelian;
    private javax.swing.JLabel tiba;
    // End of variables declaration//GEN-END:variables
}
